name: CI

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - k8s/**
      - .github/**
      - README.md
      - .gitignore
  
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  IMAGE_NAME: lupandrioli/rotten-potatoes

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    outputs:
      GITHUB_SHORT_SHA: ${{ steps.parameters.outputs.GITHUB_SHORT_SHA }}

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Parameters
        id: parameters
        run: |
          GITHUB_SHORT_SHA=${GITHUB_SHA:0:7}
          echo "GITHUB_SHORT_SHA=${GITHUB_SHORT_SHA}"
          echo "GITHUB_SHORT_SHA=${GITHUB_SHORT_SHA}" >> $GITHUB_ENV
          echo "GITHUB_SHORT_SHA=${GITHUB_SHORT_SHA}" >> $GITHUB_OUTPUT
      
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.GITHUB_SHORT_SHA }}
            ${{ env.IMAGE_NAME }}:latest
  
  update_manifest:
    needs: build_and_push
    runs-on: ubuntu-latest
    env:
      GITHUB_SHORT_SHA: ${{ needs.build_and_push.outputs.GITHUB_SHORT_SHA }}
    
    steps:
      - name: Clone gitops repo
        uses: actions/checkout@v3
        with:
          repository: 'lupandrioli/argocd-rotten-potatoes'
          ref: 'main'
          token: ${{ secrets.TOKEN_GITHUB }}
          path: 'manifests'
          persist-credentials: true

      - name: Update deployment_app.yml
        run: |
          sed -i "s|${IMAGE_NAME}.*|${IMAGE_NAME}:${GITHUB_SHORT_SHA}|g" manifests/deployment_app.yml
          echo "New tag for image '"${IMAGE_NAME}"' in deployment_app.yml:"
          grep "image:" manifests/deployment_app.yml
      
      - name: Create branch and pull request
        run: |
          BRANCH_NAME="cicd/update-image-tag-to-${{ env.GITHUB_SHORT_SHA }}"
          cd manifests
          git config --local user.name "lupandrioli"
          git config --local user.email "${{ secrets.EMAIL_GITHUB }}"
          git checkout -b $BRANCH_NAME
          git add deployment_app.yml
          git commit -m "updated tag to ${{ env.GITHUB_SHORT_SHA }}"
          git push --set-upstream origin $BRANCH_NAME
          cd -
          
          gh pr create --repo 'https://github.com/lupandrioli/argocd-rotten-potatoes' --base main --head $BRANCH_NAME \
          --title 'Update ${{ env.IMAGE_NAME }} tag to ${{ env.GITHUB_SHORT_SHA }}' \
          --body 'PR created by Github Actions'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
